---
# tasks file for ag_set_global_vars
- name: get variables from remote source
  block:
  - name: create temp dir
    local_action:
      module: tempfile
      path: /tmp
      prefix: role_temp_dir_
      state: directory
    register: tempdir
    changed_when: no
  - name: Get global vars file
    local_action:
      module: get_url
      url: https://raw.githubusercontent.com/aka7/ansible-example-global-vars/master/global_vars.yml
      dest: "{{ tempdir.path }}"
      force: yes
    run_once: yes
    changed_when: no
  - name: include_vars
    include_vars:
      file: "{{ tempdir.path }}/global_vars.yml"
    run_once: yes
    changed_when: no
  always:
  - name: Clean up temp dir
    local_action:
      module: file
      path: "{{ tempdir.path }}"
      state: absent
    changed_when: no
  check_mode: no
  become: false
